export const mockSubscriptions = [
  {
    id: "1",
    customerName: "Sarah Johnson",
    email: "sarah.j@example.com",
    plan: "Pro Plan",
    amount: 49,
    status: "authorized" as const,
    lastPayment: "Jan 15, 2025",
    nextPayment: "Feb 15, 2025",
  },
  {
    id: "2",
    customerName: "Michael Chen",
    email: "mchen@example.com",
    plan: "Basic Plan",
    amount: 29,
    status: "authorized" as const,
    lastPayment: "Jan 10, 2025",
    nextPayment: "Feb 10, 2025",
  },
  {
    id: "3",
    customerName: "Emma Wilson",
    email: "emma.w@example.com",
    plan: "Pro Plan",
    amount: 49,
    status: "paused" as const,
    lastPayment: "Dec 20, 2024",
    nextPayment: "On hold",
  },
  {
    id: "4",
    customerName: "James Rodriguez",
    email: "j.rodriguez@example.com",
    plan: "Enterprise Plan",
    amount: 99,
    status: "authorized" as const,
    lastPayment: "Jan 12, 2025",
    nextPayment: "Feb 12, 2025",
  },
  {
    id: "5",
    customerName: "Lisa Anderson",
    email: "lisa.a@example.com",
    plan: "Basic Plan",
    amount: 29,
    status: "cancelled" as const,
    lastPayment: "Dec 5, 2024",
    nextPayment: "N/A",
  },
  {
    id: "6",
    customerName: "David Kim",
    email: "dkim@example.com",
    plan: "Pro Plan",
    amount: 49,
    status: "pending" as const,
    lastPayment: "N/A",
    nextPayment: "Pending approval",
  },
  {
    id: "7",
    customerName: "Sophie Martin",
    email: "sophie.m@example.com",
    plan: "Basic Plan",
    amount: 29,
    status: "authorized" as const,
    lastPayment: "Jan 8, 2025",
    nextPayment: "Feb 8, 2025",
  },
  {
    id: "8",
    customerName: "Alex Thompson",
    email: "alex.t@example.com",
    plan: "Pro Plan",
    amount: 49,
    status: "paused" as const,
    lastPayment: "Dec 15, 2024",
    nextPayment: "On hold",
  },
  {
    id: "9",
    customerName: "Maria Garcia",
    email: "maria.g@example.com",
    plan: "Enterprise Plan",
    amount: 99,
    status: "authorized" as const,
    lastPayment: "Jan 14, 2025",
    nextPayment: "Feb 14, 2025",
  },
  {
    id: "10",
    customerName: "Robert Lee",
    email: "robert.l@example.com",
    plan: "Basic Plan",
    amount: 29,
    status: "pending" as const,
    lastPayment: "N/A",
    nextPayment: "Pending approval",
  },
]

export const mockCustomers = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.j@example.com",
    subscriptions: 1,
    totalValue: 49,
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "mchen@example.com",
    subscriptions: 1,
    totalValue: 29,
  },
  {
    id: "3",
    name: "Emma Wilson",
    email: "emma.w@example.com",
    subscriptions: 1,
    totalValue: 49,
  },
  {
    id: "4",
    name: "James Rodriguez",
    email: "j.rodriguez@example.com",
    subscriptions: 2,
    totalValue: 148,
  },
  {
    id: "5",
    name: "Lisa Anderson",
    email: "lisa.a@example.com",
    subscriptions: 0,
    totalValue: 0,
  },
  {
    id: "6",
    name: "David Kim",
    email: "dkim@example.com",
    subscriptions: 1,
    totalValue: 49,
  },
]
